global:
  device: 3

model:
  name: vit_l_16
  pretrained: True

training:
  batch_size: 64
  steps_per_epoch: 256
  epochs: 100000
  loss: Huber
  lr: 1e-4
  optimizer: Adam

validation:
  batch_size: 16
  steps_per_epoch: 256
  loss: L1

dataset:
  name: SapphireDataset
  image_size: 224
  crop_size: 64
  num_workers: 8

logging:
  exp_name: vit_l_16_all_heads_long_run
  result_columns:  ["global_train_step", "global_val_step", "epoch", "train_loss", "val_loss", "z"]
  log_figures: false
  log_interval: 256