global:
  device: 0

model:
  name: resnet152
  pretrained: True

training:
  batch_size: 16
  steps_per_epoch: 256
  epochs: 2000
  loss: Huber
  lr: 1e-7
  optimizer: Adam

validation:
  batch_size: 16
  steps_per_epoch: 256
  loss: L1

dataset:
  name: SapphireDataset
  image_size: 224
  crop_size: 64
  num_workers: 8

logging:
  exp_name: resnet-huber-corrected-val
  result_columns:  ["global_train_step", "global_val_step", "epoch", "train_loss", "val_loss", "z"]
  log_figures: false
  log_interval: 256