global:
  device: 0

model:
  name: ae
  pretrained: True

training:
  batch_size: 16
  steps_per_epoch: 256
  epochs: 2000
  loss: MSE
  lr: 1e-3
  optimizer: Adam

validation:
  batch_size: 16
  steps_per_epoch: 256
  loss: L1

dataset:
  name: SapphireDataset
  image_size: 224
  crop_size: 64
  num_workers: 0

logging:
  root: "/playpen/mufan/levi/tianlong-chen-lab/material-super-resolution/__exps__/y-task-formulations/1. P(y | y_sparse)"
  exp_name: ae_y_bar_y_sparse
  result_columns: ["global_train_step", "global_val_step", "epoch", "train_loss", "val_loss", "z"]
  save_weights: true
  save_only_best_weights: true
  enable_tensorboard: false
  log_figures: false
  log_interval: 256