global:
  device: 4

model:
  variant: ResNet152
  pretrained: True

training:
  batch_size: 16
  steps_per_epoch: 256
  epochs: 100
  loss: MSE
  lr: 1e-4
  optimizer: Adam

validation:
  batch_size: 16
  steps_per_epoch: 256
  loss: L1

dataset:
  name: SapphireDataset
  image_size: 256
  crop_size: 64

logging:
  result_columns:  ["global_train_step", "global_val_step", "epoch", "train_loss", "val_loss"]