dataset:
    crop_size: 128
    image_size: 512
    masking_ratio: 1
    name: MOS2SEFDataset
    num_workers: 0
global:
    device: 0
    formulation: p(y|y_sparse)
    mode: train
logging:
    enable_tensorboard: false
    exp_name: ''
    log_figures: false
    log_interval: 1
    result_columns:
    - global_train_step
    - global_val_step
    - epoch
    - train_loss
    - val_loss
    - z
    root: ''
    save_only_best_weights: true
    save_weights: true
model:
    config: model-configs/swinir.yaml
    name: ours
    pretrained: true
    weights: null
surrogate:
    name: older_surrogate_mh
    weights: ''
training:
    batch_size: 1
    epochs: 50
    loss: L1
    lr: 1e-4
    optimizer: Adam
    steps_per_epoch: 1024
validation:
    batch_size: 1
    loss: L1
    steps_per_epoch: 256
