global:
  device: 0
  mode: eval  # ['train', 'eval']
  formulation: p(y|y_sparse_benchmark)

model:
  name: swinir
  pretrained: True
  weights: /playpen/mufan/levi/tianlong-chen-lab/material-super-resolution/__exps__/y-task-formulations/4. pre-training/2025-01-19_13-08-57_swinir_p_y_bar_y_sparse_50/swinir_p_y_bar_y_sparse_50_best.pt

validation:
  batch_size: 1
  steps_per_epoch: 1000
  loss: InpaintingL1

dataset:
  name: SapphireDataset
  image_size: 224
  crop_size: 128
  num_workers: 0
  masking_ratio: 1

logging:
  root: /playpen/mufan/levi/tianlong-chen-lab/material-super-resolution/__exps__/y-task-formulations/6. p(y | y_sparse)/6a. benchmarks
  exp_name: swinir_p_y_bar_y_sparse_50_128x128
  result_columns: ["step", "mae","mse", "psnr", "ssim"]
  save_weights: true
  save_only_best_weights: true
  enable_tensorboard: false
  log_figures: false
  log_interval: 1