model:
  variant: ResNet152
  pretrained: True

training:
  batch_size: 4
  steps_per_epoch: 100
  epochs: 3
  loss: MSELoss
  lr: 1e-4
  optimizer: Adam

validation:
  batch_size: 32
  steps_per_epoch: 100
  loss: MSELoss

dataset:
  name: SapphireDataset
  image_size: 256
  crop_size: 64

logging:
  result_columns:  ["global_train_step", "global_val_step", "epoch", "train_loss", "val_loss"]